### ISSUE TITLE
I cant get it to work

### ISSUE THREAD

**Issue by IoakeimSogiakas** [MuhammedMagdyy/Dentist-Clinic-Management#1]
I am very new to SQL how do I set up my variable correctly? Even if I set them up (correctly?) and then run the thing I just get 
![image](https://github.com/user-attachments/assets/b64821c7-67f3-4a75-9438-d8b64eafcaac)
Cannot GET /

Any help would be appreciated!n

**Comment by MuhammedMagdyy** [comment]
Hello @IoakeimSogiakas,

I have made some changes on my local machine, let me check and I will contact you ASAP

Thank you!

**Comment by MuhammedMagdyy** [comment]
Hello @IoakeimSogiakas again!,
Please tell me all the steps after cloning this repository.
Make sure you have installed [MySQL](https://dev.mysql.com/downloads/installer/) and added your env variables correctly
Thank you!

**Comment by IoakeimSogiakas** [comment]
Hi I installed mySQL (I tried both Linux and Windows) I set up a password and I copied the env.exmple file and change the
DB_NAME=test
DB_USER=test
DB_PASS=test123
DB_HOST=test
DB_DIALECT=test

To
DB_NAME=smilesthetics (the database name)
DB_USER=root
DB_PASS=sql pass
DB_HOST=localhost
DB_DIALECT=mysql

And then this ADMIN_NAME=test
ADMIN_ROLE=test
ADMIN_EMAIL=example@example.com
ADMIN_PASSWORD=secretpassword

To ADMIN_NAME=athina
ADMIN_ROLE=admin
ADMIN_EMAIL=smilesthetics@gmail.com
ADMIN_PASSWORD=test123

**Comment by MuhammedMagdyy** [comment]
Hello again,

Let me check and I'll ping asap, also I'll provide some steps to make it better

Thank you for your time.

**Comment by IoakeimSogiakas** [comment]
Hi thank you for the help. One heads up. At the moment I am on vacation till Monday so I won't be able to test anything...

**Comment by MuhammedMagdyy** [comment]
That is no problem. I will provide the steps, and let me know when you face any issues.

**Comment by IoakeimSogiakas** [comment]
Thank you

**Comment by MuhammedMagdyy** [comment]
Hello @IoakeimSogiakas,

I will provide some steps, that lead to a successful connection inshallah.

- Install MySQL, open CMD, run `mysql -u root -p`, and write your password. This will check that you've successfully installed MySQL. If any errors appear, please search or let me know.
- Install a database tool like `DBeaver` and create a MySQL connection with the data you've added in .env.
- Open the project and run `npm start` to run the development mode.

If you face any issues, please let me know.

**Comment by IoakeimSogiakas** [comment]
Thank you as soon as I get back I will give it a shot and keep you updated

**Comment by IoakeimSogiakas** [comment]
Hi me again. I am back i did everything from scratch. I installed MySQL and added DBearver which says if i hit test
![image](https://github.com/user-attachments/assets/8f77553c-6f90-42ec-bbad-f769bfbc1629)

However I still get the `Cannot GET /` error. 
Here is the dump of what the terminal give after i run npm start

> npm start
graduation-project@1.0.0 start
nodemon app.js
[nodemon] 3.0.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node app.js`
Server running on port 3000
Executing (default): SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'clinics' AND TABLE_SCHEMA = 'smilesthetics'
Executing (default): CREATE TABLE IF NOT EXISTS `clinics` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255) NOT NULL UNIQUE, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `clinics`
Executing (default): SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'dentists' AND TABLE_SCHEMA = 'smilesthetics'
Executing (default): CREATE TABLE IF NOT EXISTS `dentists` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255) NOT NULL, `email` VARCHAR(255) NOT NULL UNIQUE, `phone` VARCHAR(255) NOT NULL UNIQUE, `nationalId` VARCHAR(255) NOT NULL UNIQUE, `worksIn` VARCHAR(255) NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `dentists`
Executing (default): SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'roles' AND TABLE_SCHEMA = 'smilesthetics'
Executing (default): CREATE TABLE IF NOT EXISTS `roles` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255) NOT NULL UNIQUE, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;  
Executing (default): SHOW INDEX FROM `roles`
Executing (default): SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'users' AND TABLE_SCHEMA = 'smilesthetics'
Executing (default): CREATE TABLE IF NOT EXISTS `users` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255) NOT NULL, `email` VARCHAR(255) NOT NULL UNIQUE, `password` VARCHAR(255) NOT NULL, `verificationCode` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `roleId` INTEGER, PRIMARY KEY (`id`), FOREIGN KEY (`roleId`) REFERENCES `roles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `users`
Executing (default): SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'patients' AND TABLE_SCHEMA = 'smilesthetics'
Executing (default): CREATE TABLE IF NOT EXISTS `patients` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255) NOT NULL, `age` VARCHAR(255) NOT NULL, `phone` VARCHAR(255) NOT NULL UNIQUE, `gender` VARCHAR(255) NOT NULL, `address` VARCHAR(255) NOT NULL, `city` VARCHAR(255) NOT NULL, `nationalId` VARCHAR(255) NOT NULL UNIQUE, `nationality` VARCHAR(255) NOT NULL, `maritalStatus` VARCHAR(255) NOT NULL, `occupation` VARCHAR(255) NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `createdBy` INTEGER, PRIMARY KEY (`id`), FOREIGN KEY (`createdBy`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `patients`
Executing (default): SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'outpatients' AND TABLE_SCHEMA = 'smilesthetics'
Executing (default): CREATE TABLE IF NOT EXISTS `outpatients` (`id` INTEGER NOT NULL auto_increment , `chiefComplaint` VARCHAR(255) NOT NULL, `medicalHistory` VARCHAR(255) NOT NULL, `diagnosis` VARCHAR(255) NOT NULL, `extraOral` VARCHAR(255) NOT NULL, `intraOral` VARCHAR(255) NOT NULL, `upperRight` VARCHAR(255), `upperLeft` VARCHAR(255), `downRight` VARCHAR(255), `downLeft` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `patientId` INTEGER, `createdBy` INTEGER, `dentistId` INTEGER, `transferedId` INTEGER, PRIMARY KEY (`id`), FOREIGN KEY (`patientId`) REFERENCES `patients` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`createdBy`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`dentistId`) REFERENCES `dentists` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`transferedId`) REFERENCES `clinics` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `outpatients`
Executing (default): SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'specializeds' AND TABLE_SCHEMA = 'smilesthetics'
Executing (default): CREATE TABLE IF NOT EXISTS `specializeds` (`id` INTEGER NOT NULL auto_increment , `examination` VARCHAR(255) NOT NULL, `diagnosis` VARCHAR(255) NOT NULL, `radiographicExam` VARCHAR(255) NOT NULL, `treatment` VARCHAR(255) NOT NULL, `treatmentPlan` VARCHAR(255) NOT NULL, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `dentistId` INTEGER, `patientId` INTEGER, `clinicId` INTEGER, `createdBy` INTEGER, PRIMARY KEY (`id`), FOREIGN KEY (`dentistId`) REFERENCES `dentists` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`patientId`) REFERENCES `patients` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`clinicId`) REFERENCES `clinics` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`createdBy`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `specializeds`
Executing (default): SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'appointments' AND TABLE_SCHEMA = 'smilesthetics'
Executing (default): CREATE TABLE IF NOT EXISTS `appointments` (`id` INTEGER NOT NULL auto_increment , `status` INTEGER NOT NULL DEFAULT 0, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `clinicId` INTEGER, `patientId` INTEGER, `transferedTo` INTEGER, PRIMARY KEY (`id`), FOREIGN KEY (`clinicId`) REFERENCES `clinics` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`patientId`) REFERENCES `patients` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`transferedTo`) REFERENCES `appointments` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `appointments`
Database connected successfully
Executing (default): SELECT count(*) AS `count` FROM `roles` AS `role`;
Executing (default): SELECT count(*) AS `count` FROM `users` AS `user`;
Executing (default): INSERT INTO `roles` (`id`,`name`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?,?);
Executing (default): INSERT INTO `users` (`id`,`name`,`email`,`password`,`createdAt`,`updatedAt`,`roleId`) VALUES (DEFAULT,?,?,?,?,?,?);


also here is the setting in my `.env` 

> `#` Dentist Clinic Management
PORT=3000
`#` Database
DB_NAME=smilesthetics
DB_USER=root
DB_PASS=Superstrongpassword 
DB_HOST=localhost
DB_DIALECT=mysql
`#` JWT left as default i don't know what to put here
JWT_KEY=secretkey
JWT_EXPIRES_IN=1d
`#` SENDGRID left as default i don't know what to put here
SENDGRID_API_KEY=somekey
SENDGRID_EMAIL=example@example.com
`#` ADMIN CONFIGIRATION
ADMIN_NAME=athina
ADMIN_ROLE=admin
ADMIN_EMAIL=smilesthetics@gmail.com
ADMIN_PASSWORD=test123

**Comment by MuhammedMagdyy** [comment]
Hello!
Yup, it now works fine, you get this because there is no endpoint to handle /
You can create a new one in `app.js`  above `app.listen', and here's the code if you want to try it
```
app.get('/', (_req, res) => {
  res.status(200).json({ message: 'Hello from localhost' });
});
})
```

**Comment by IoakeimSogiakas** [comment]
Ok i get that but on your read me the server looks way different on my it is just displaying Hello from LocalHost. Do i have to visit a different IP address?
Or is the server just the backbone?

**Comment by IoakeimSogiakas** [comment]
I never get the rest like  'Database connected successfully or thing like that

**Comment by MuhammedMagdyy** [comment]
In the readme, I added the front end of the app only...
But for now, it works fine with you, you can edit the source code and add yours then test it

**Comment by IoakeimSogiakas** [comment]
Ahhh ok got it thank you!
